### ISSUE TITLE
/issues doesnt work, Error 500 after rebuild database

### ISSUE THREAD

**Issue by joshuatly** [krateng/maloja#16] opened 2020-05-26 11:27 UTC
Hi, I have problem where the /issues page doesnt work.
Whenever I click something, it will show on debug the error below:

```
[debug] Generated page issues in 1.3312759399414062s (Python+HTML)
Traceback (most recent call last):
  File "/home/joshua/.local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/home/joshua/.local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/home/joshua/.local/lib/python3.7/site-packages/nimrodel/_api.py", line 134, in route
    result = self.handle(nodes,reqmethod,keys,headers)
  File "/home/joshua/.local/lib/python3.7/site-packages/nimrodel/_apifunction.py", line 79, in handle
    return func(**querykeys,**pathkeys)
  File "/home/joshua/.local/lib/python3.7/site-packages/maloja/database.py", line 720, in newrule
    tsv.add_entry("rules/webmade.tsv",[k for k in keys])
  File "/home/joshua/.local/lib/python3.7/site-packages/doreah/_internal.py", line 27, in newfunc
    return func(*args,**realargs)
  File "/home/joshua/.local/lib/python3.7/site-packages/doreah/tsv.py", line 111, in add_entry
    create(filename)
  File "/home/joshua/.local/lib/python3.7/site-packages/doreah/tsv.py", line 101, in create
    open(filename,"w").close()
FileNotFoundError: [Errno 2] No such file or directory: 'rules/webmade.tsv'
```

I tried to touch /home/joshua/.local/share/maloja/rules/webmade.tsv
Still same result.

Before enabling debug, here is the symptom that lead me to troubleshoot with debug:
After I done my clicks on /issues pages, after I rebuild the database, I can no longer visit the page properly, it will give me ERROR 500, and i have to restart maloja server to get it to work again

Below is the error of that in error log

```
2020/05/26 11:17:28  Error in website generation: (<class 'IndexError'>, IndexError('list index out of range'), <traceback object at 0x7fd8d67f44c8>)
```

I run Debian and run maloja by pip installing it, on user joshua, and not using any virtual env. This container is just for this service alone.

**Comment by krateng** [comment] 2020-05-28 15:27
The missing file should be fixed, the database rebuild is a bit of a dodgy construct in the first place - I'll see if I can fix it, otherwise I might have to completely remove that functionality and just require a server restart.

**Comment by ICTman1076** [comment] 2020-06-17 16:36
Related issue, I'm not sure if it's worth its own but I was unable to get the rebuild to work behind Cloudflare. Only when I forced it to go direct to the server did it actually work,

**Closed** 2020-06-18 13:16 UTC

**Comment by krateng** [comment] 2020-06-18 13:18
The database rebuild should now work as far as I can tell, let me know if there are still issues.

@ICTman1076 could you try with new new version just to check if that happens to be fixed with that as well?

**Comment by ICTman1076** [comment] 2020-06-21 10:13
> @ICTman1076 could you try with the new new version just to check if that happens to be fixed with that as well?

It did seem to work, however I should note that there were no issues or rule changes that the database would need to rebuild so I can't reproduce exactly. Version 2.4.13

Thank you, by the way, for a great piece of software and continuing to support it :)
