### ISSUE TITLE
Use stdout for logging

### ISSUE THREAD

**Issue by Derkades** [krateng/maloja#19] opened 2020-06-06 16:02 UTC
When running in a docker container, usually log messages should be handled by docker instead of logged to a file by the application.

For right now I've done this, but it feels hacky:
```
LOGS="${MALOJA_DATA_DIRECTORY}/logs"
mkdir -p ${LOGS}
ln -s /dev/stdout "${LOGS}/debug.log"
ln -s /dev/stdout "${LOGS}/maloja.server.log"
ln -s /dev/stdout "${LOGS}/maloja.database.log"
ln -s /dev/stdout "${LOGS}/maloja.utilities.log"
```

Is there an option (environment variable) to disable all file logging and use stdout instead?

**Comment by krateng** [comment] 2020-06-06 16:19
The log function should both write the message to file and print it to stdout. Does this not work?

**Comment by Derkades** [comment] 2020-06-06 17:12
No, when I run `maloja run` there is no output

**Comment by krateng** [comment] 2020-06-06 18:01
I have honestly no idea what could cause that. Is the same true if you run `python3 -m maloja.controller run` and `python3 -m maloja.server`?

**Comment by Derkades** [comment] 2020-06-06 21:39
I did some testing and it seems that it doesn't log only when `MALOJA_SKIP_SETUP=true` is set. Without this it does log to stdout, even if you run it once without and later with the environment variable set.

**Comment by krateng** [comment] 2020-06-07 12:42
I can't seem to reproduce this, even when setting MALOJA_SKIP_SETUP=true from the start. Since it now works for you correctly, I'm closing this for now, but if anyone else encounters this problem, please let me know.

**Closed by krateng** 2020-06-07 12:42 UTC

**Comment by Derkades** [comment] 2020-06-09 10:53
I have no idea what is going on. I can't reproduce using
```
docker run -it python:3 /bin/bash
pip install malojaserver
export MALOJA_SKIP_SETUP=true
export MALOJA_DATA_DIRECTORY=/data
maloja run
```
or
```
docker run -it python:3-alpine /bin/sh
apk add --no-cache gcc libxml2-dev libxslt-dev libc-dev linux-headers
pip install malojaserver
export MALOJA_SKIP_SETUP=true
export MALOJA_DATA_DIRECTORY=/data
maloja run
```

but I can using the dockerfile
```Dockerfile
FROM python:3-alpine

RUN apk add --no-cache --virtual .build-deps \
            gcc \
            libxml2-dev \
            libxslt-dev \
            libc-dev \
            linux-headers && \
    pip install malojaserver && \
    apk del .build-deps

ENV MALOJA_SKIP_SETUP=true
ENV MALOJA_DATA_DIRECTORY=/data

EXPOSE 42010
VOLUME [ "/data" ]
WORKDIR "/data"

ENTRYPOINT [ "maloja", "run" ]
```

I don't think it's a maloja issue so you can ignore this. However, could there still be an option to disable file logging by maloja?

**Comment by krateng** [comment] 2020-06-13 15:35
Should now work with the option `LOGGING` in the settings file or `MALOJA_LOGGING` as environment variable.
